name: 'Development Pipeline'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  lint:
    permissions:
      contents: write
    uses: ./.github/workflows/lint.yml

  push-docker-image:
    needs: [tests, lint]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/push-image.yml
    secrets: inherit

  deploy:
    needs: [push-docker-image]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit